### ISSUE TITLE
The topic is not visible in isaac sim

### ISSUE THREAD

**Issue by 7zjatl7** [leonlime/scout_v2_isaac#3]
Hello, I am going to use scout_v2 just like you to make Issac sim work through ROS2.

But  https://leonlime.github.io/posts/isaac2/, I imported scout_v2_simulation.usd as shown in  but if I check the ros2 topic list, I don't see any topic.

Is there anything else I need to check?

I am using isacsim 2022.1.1 version and it is ros2 foxy version.

**Comment by DarK404** [comment]
Same issue I solve it with [this ](https://github.com/eProsima/Fast-DDS/issues/3000#issuecomment-1281326568) solution

**Comment by leonlime** [comment]
Sorry for the late response, today I updated to ROS2 Humble and Isaac 2022.2.1. Can you check if it is working now?
